### ISSUE TITLE
GIT repository seems corrupted

### ISSUE THREAD

**Issue by smalot** [opensolutions/OSS-Framework#41]
When I try to clone your repo, I encountered this issue:

    root@debian /tmp $ git clone git@github.com:opensolutions/OSS-Framework.git
    Cloning into OSS-Framework...
    remote: Counting objects: 2283, done.
    remote: Compressing objects: 100% (6/6), done.
    remote: Total 2283 (delta 6), reused 5 (delta 5), pack-reused 2272
    Receiving objects: 100% (2283/2283), 10.49 MiB | 435 KiB/s, done.
    Resolving deltas: 100% (1555/1555), done.
    error: refs/remotes/origin/master does not point to a valid object!
    error: Trying to write ref refs/heads/master with nonexistant object baf803ff8a476cb5937e5e6daeea8fb479679bf5
    fatal: Cannot update the ref 'HEAD'.

But if I fork your repo and try to clone the new one, everything is fine.

**Comment by barryo** [comment]
Hmmm... I don't get that issue:

```sh
barryo@mac1:~/tmp $ git clone git@github.com:opensolutions/OSS-Framework.git
Cloning into 'OSS-Framework'...
remote: Counting objects: 2398, done.
remote: Total 2398 (delta 0), reused 0 (delta 0), pack-reused 2398
Receiving objects: 100% (2398/2398), 10.51 MiB | 1.97 MiB/s, done.
Resolving deltas: 100% (1624/1624), done.
Checking connectivity... done.
barryo@mac1:~/tmp $ git --version
git version 2.3.0
```

**Comment by smalot** [comment]
I'm still having the same issue (done 5 minutes ago).

Do you know why we have a different "Counting objects" ?
Should it be a explaination of why it works for you and not for me ?

````
- remote: Counting objects: 2283, done.
+ remote: Counting objects: 2398, done.
````

**Comment by barryo** [comment]
What version of git? I'm on 2.3.0.

**Comment by smalot** [comment]
Oh ! Nice idea.

root@sebastien-debian /tmp $ git --version
git version 1.7.2.5

It's strange because the git clone works with the forked repository.
But you're right, I'll try first to update my git version.

**Comment by barryo** [comment]
Yeah, I've seen these kind of issues with older versions.
